
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AT BOOLEAN_LITERAL CLASS_NAME COLON COMMA ENUM IDENT INSTANCE_NAME LBRACE LBRACKET LEFT_ARROW LPAREN META_ATTRIBUTE NATIVE_TYPE NEW_DATATYPE NUMBER PACKAGE RANGE_DOTS RBRACE RBRACKET RELATION_NAME RIGHT_ARROW RPAREN STAR STRINGstart : packagepackage : PACKAGE IDENT LBRACE package_body RBRACE\n               | PACKAGE CLASS_NAME LBRACE package_body RBRACEpackage_body : package_item_list\n                    | emptypackage_item_list : package_item_list package_item\n                         | package_itempackage_item : enum_decl\n                    | class_decl\n                    | datatype_decl\n                    | generalization\n                    | relation_externalclass_decl : CLASS_NAME COLON IDENT class_blockclass_block : LBRACE class_body RBRACE\n                   | emptyclass_body : class_body class_element\n                  | class_elementclass_element : attribute\n                     | relation_internalattribute : RELATION_NAME COLON IDENT\n                 | RELATION_NAME COLON CLASS_NAME\n                 | RELATION_NAME COLON NATIVE_TYPE\n                 | RELATION_NAME COLON NEW_DATATYPEdatatype_decl : NEW_DATATYPE LBRACE attr_list RBRACEattr_list : attribute\n                 | attr_list attributeenum_decl : ENUM CLASS_NAME LBRACE enum_items RBRACEenum_item : CLASS_NAME\n                 | IDENTenum_items : enum_item\n                  | enum_items enum_itemgeneralization : CLASS_NAME CLASS_NAME genset_blockgenset_block : LBRACE genset_body RBRACEgenset_body : IDENT COLON IDENT\n                   | IDENT COLON IDENT COMMA IDENTrelation_internal : IDENT LBRACKET RANGE_DOTS RBRACKET LEFT_ARROW LBRACKET RANGE_DOTS RBRACKET CLASS_NAMErelation_external : AT IDENT IDENT CLASS_NAME RIGHT_ARROW CLASS_NAMEempty :'
    
_lr_action_items = {'PACKAGE':([0,],[3,]),'$end':([1,2,22,29,],[0,-1,-2,-3,]),'IDENT':([3,20,26,28,30,32,38,39,40,41,45,49,52,54,55,56,57,58,60,61,62,63,67,70,78,],[4,28,33,37,41,43,-28,41,-30,-29,59,60,-31,65,59,-17,-18,-19,-20,-21,-22,-23,-16,72,-36,]),'CLASS_NAME':([3,6,7,9,11,12,13,14,15,16,17,18,23,30,31,33,37,38,39,40,41,44,46,47,49,51,52,53,64,66,69,77,],[5,18,18,18,-7,-8,-9,-10,-11,-12,24,25,-6,38,-32,-38,50,-28,38,-30,-29,-13,-15,-24,61,-27,-31,-33,69,-14,-37,78,]),'LBRACE':([4,5,19,24,25,33,],[6,7,27,30,32,45,]),'RBRACE':([6,7,8,9,10,11,12,13,14,15,16,21,23,31,33,34,35,38,39,40,41,42,44,46,47,48,51,52,53,55,56,57,58,60,61,62,63,65,66,67,69,72,78,],[-38,-38,22,-4,-5,-7,-8,-9,-10,-11,-12,29,-6,-32,-38,47,-25,-28,51,-30,-29,53,-13,-15,-24,-26,-27,-31,-33,66,-17,-18,-19,-20,-21,-22,-23,-34,-14,-16,-37,-35,-36,]),'ENUM':([6,7,9,11,12,13,14,15,16,23,31,33,44,46,47,51,53,66,69,],[17,17,17,-7,-8,-9,-10,-11,-12,-6,-32,-38,-13,-15,-24,-27,-33,-14,-37,]),'NEW_DATATYPE':([6,7,9,11,12,13,14,15,16,23,31,33,44,46,47,49,51,53,66,69,],[19,19,19,-7,-8,-9,-10,-11,-12,-6,-32,-38,-13,-15,-24,63,-27,-33,-14,-37,]),'AT':([6,7,9,11,12,13,14,15,16,23,31,33,44,46,47,51,53,66,69,],[20,20,20,-7,-8,-9,-10,-11,-12,-6,-32,-38,-13,-15,-24,-27,-33,-14,-37,]),'COLON':([18,36,43,],[26,49,54,]),'RELATION_NAME':([27,34,35,45,48,55,56,57,58,60,61,62,63,67,78,],[36,36,-25,36,-26,36,-17,-18,-19,-20,-21,-22,-23,-16,-36,]),'NATIVE_TYPE':([49,],[62,]),'RIGHT_ARROW':([50,],[64,]),'LBRACKET':([59,74,],[68,75,]),'COMMA':([65,],[70,]),'RANGE_DOTS':([68,75,],[71,76,]),'RBRACKET':([71,76,],[73,77,]),'LEFT_ARROW':([73,],[74,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'start':([0,],[1,]),'package':([0,],[2,]),'package_body':([6,7,],[8,21,]),'package_item_list':([6,7,],[9,9,]),'empty':([6,7,33,],[10,10,46,]),'package_item':([6,7,9,],[11,11,23,]),'enum_decl':([6,7,9,],[12,12,12,]),'class_decl':([6,7,9,],[13,13,13,]),'datatype_decl':([6,7,9,],[14,14,14,]),'generalization':([6,7,9,],[15,15,15,]),'relation_external':([6,7,9,],[16,16,16,]),'genset_block':([25,],[31,]),'attr_list':([27,],[34,]),'attribute':([27,34,45,55,],[35,48,57,57,]),'enum_items':([30,],[39,]),'enum_item':([30,39,],[40,52,]),'genset_body':([32,],[42,]),'class_block':([33,],[44,]),'class_body':([45,],[55,]),'class_element':([45,55,],[56,67,]),'relation_internal':([45,55,],[58,58,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> start","S'",1,None,None,None),
  ('start -> package','start',1,'p_start','parser_tonto.py',30),
  ('package -> PACKAGE IDENT LBRACE package_body RBRACE','package',5,'p_package','parser_tonto.py',39),
  ('package -> PACKAGE CLASS_NAME LBRACE package_body RBRACE','package',5,'p_package','parser_tonto.py',40),
  ('package_body -> package_item_list','package_body',1,'p_package_body','parser_tonto.py',47),
  ('package_body -> empty','package_body',1,'p_package_body','parser_tonto.py',48),
  ('package_item_list -> package_item_list package_item','package_item_list',2,'p_package_item_list','parser_tonto.py',53),
  ('package_item_list -> package_item','package_item_list',1,'p_package_item_list','parser_tonto.py',54),
  ('package_item -> enum_decl','package_item',1,'p_package_item','parser_tonto.py',63),
  ('package_item -> class_decl','package_item',1,'p_package_item','parser_tonto.py',64),
  ('package_item -> datatype_decl','package_item',1,'p_package_item','parser_tonto.py',65),
  ('package_item -> generalization','package_item',1,'p_package_item','parser_tonto.py',66),
  ('package_item -> relation_external','package_item',1,'p_package_item','parser_tonto.py',67),
  ('class_decl -> CLASS_NAME COLON IDENT class_block','class_decl',4,'p_class_decl','parser_tonto.py',76),
  ('class_block -> LBRACE class_body RBRACE','class_block',3,'p_class_block','parser_tonto.py',82),
  ('class_block -> empty','class_block',1,'p_class_block','parser_tonto.py',83),
  ('class_body -> class_body class_element','class_body',2,'p_class_body','parser_tonto.py',88),
  ('class_body -> class_element','class_body',1,'p_class_body','parser_tonto.py',89),
  ('class_element -> attribute','class_element',1,'p_class_element','parser_tonto.py',94),
  ('class_element -> relation_internal','class_element',1,'p_class_element','parser_tonto.py',95),
  ('attribute -> RELATION_NAME COLON IDENT','attribute',3,'p_attribute','parser_tonto.py',100),
  ('attribute -> RELATION_NAME COLON CLASS_NAME','attribute',3,'p_attribute','parser_tonto.py',101),
  ('attribute -> RELATION_NAME COLON NATIVE_TYPE','attribute',3,'p_attribute','parser_tonto.py',102),
  ('attribute -> RELATION_NAME COLON NEW_DATATYPE','attribute',3,'p_attribute','parser_tonto.py',103),
  ('datatype_decl -> NEW_DATATYPE LBRACE attr_list RBRACE','datatype_decl',4,'p_datatype_decl','parser_tonto.py',114),
  ('attr_list -> attribute','attr_list',1,'p_attr_list','parser_tonto.py',120),
  ('attr_list -> attr_list attribute','attr_list',2,'p_attr_list','parser_tonto.py',121),
  ('enum_decl -> ENUM CLASS_NAME LBRACE enum_items RBRACE','enum_decl',5,'p_enum_decl','parser_tonto.py',130),
  ('enum_item -> CLASS_NAME','enum_item',1,'p_enum_item','parser_tonto.py',136),
  ('enum_item -> IDENT','enum_item',1,'p_enum_item','parser_tonto.py',137),
  ('enum_items -> enum_item','enum_items',1,'p_enum_items','parser_tonto.py',141),
  ('enum_items -> enum_items enum_item','enum_items',2,'p_enum_items','parser_tonto.py',142),
  ('generalization -> CLASS_NAME CLASS_NAME genset_block','generalization',3,'p_generalization','parser_tonto.py',149),
  ('genset_block -> LBRACE genset_body RBRACE','genset_block',3,'p_genset_block','parser_tonto.py',155),
  ('genset_body -> IDENT COLON IDENT','genset_body',3,'p_genset_body','parser_tonto.py',160),
  ('genset_body -> IDENT COLON IDENT COMMA IDENT','genset_body',5,'p_genset_body','parser_tonto.py',161),
  ('relation_internal -> IDENT LBRACKET RANGE_DOTS RBRACKET LEFT_ARROW LBRACKET RANGE_DOTS RBRACKET CLASS_NAME','relation_internal',9,'p_relation_internal','parser_tonto.py',170),
  ('relation_external -> AT IDENT IDENT CLASS_NAME RIGHT_ARROW CLASS_NAME','relation_external',6,'p_relation_external','parser_tonto.py',176),
  ('empty -> <empty>','empty',0,'p_empty','parser_tonto.py',183),
]
